version: '3'

services:
  koroche-app:
    container_name: "koroche-app"
    build:
      context: .
      dockerfile: Dockerfile

  koroche-frontend:
    container_name: "koroche-frontend"
    build:
      context: .
      dockerfile: Dockerfile-backend
    
    ports:
    - "80:5173"

  koroche-nginx-server:
    container_name: "koroche-nginx-server"
    build:
      context: ./nginx
      dockerfile: Dockerfile

    ports:
      - "80:23002"