[tool.black]
line-length = 120
verbose = 1
color = true
exclude = '''
/(
  | .mypy_cache
  | .pytest_cache
  | .venv
  | venv
)/
'''

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 120
src_paths = ["src"]
skip = [".mypy_cache", "pytest_cache" , "venv", ".venv"]

[tool.flake8]
exclude=".git,./tests,./venv,./.venv,./build"
max-line-length = 120
rst-roles = "class, func, ref"
rst-directives = "envvar, exception"
extend-ignore = "E203,E501,W503,D100,D105,D107,D400,D104,DAR401,D401"
per-file-ignores = "__init__.py:F401"
docstring-convention = "pep257"
docstring_style = "sphinx"

# Disallow dynamic typing
disallow_any_unimported = false
disallow_subclassing_any = true

# Disallow untyped definitions and calls
disallow_untyped_calls = true
disallow_untyped_defs = false
disallow_any_generics = false
disallow_incomplete_defs = true

# Configuring warnings
warn_unused_ignores = true
warn_redundant_casts = true
