app:
  version: "0.1.0"
  api_version: "v1"
  debug: true
  host: "127.0.0.1"
  port: 23003

applog:
  log_format: "%(asctime)s %(service_name)s %(env_type)s %(levelname)s: %(message)s"
  handlers:
    stream:
      handler: 'stdout'
  level: 'DEBUG'

net:
  base_api_url: "http://localhost:19097"
  backoff:
    max_tries_n: 3
    code_forcelist: [408, 429, 500, 502, 503, 504]
